# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.SmallIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('province', models.CharField(max_length=32)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm01.Department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
