# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-17 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
